from django.test import TestCase

# Create your tests here.
from django.test import TestCase
from django.urls import reverse
from django.contrib.auth.models import User

class ProcurementFlowTests(TestCase):
    def test_make_request(self): ...
    def test_approve_request(self): ...
    def test_make_order(self): ...
    def test_confirm_goods(self): ...

class InvoiceFlowTests(TestCase):
    def test_add_invoice(self): ...
    def test_approve_invoice(self): ...
    def test_pay_invoice(self): ...

class DashboardTests(TestCase):
    def test_admin_dashboard_view(self): ...
