# Generated by Django 5.2.7 on 2025-10-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resourcecategory",
            options={
                "verbose_name": "Resource Category",
                "verbose_name_plural": "Resource Categories",
            },
        ),
    ]
