# Generated by Django 5.2.7 on 2025-11-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wellnesstest",
            name="department",
        ),
        migrations.RemoveField(
            model_name="wellnesstest",
            name="employee",
        ),
        migrations.DeleteModel(
            name="WellnessHub",
        ),
        migrations.DeleteModel(
            name="WellnessTest",
        ),
    ]
