# Generated by Django 5.2.7 on 2026-01-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="last_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
