# Generated by Django 5.2.6 on 2025-11-26 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='mood_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('article', 'Article'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media_files/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media_thumbs/%Y/%m/%d/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Optional duration in seconds for audio/video.', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['media_type'], name='obeeomaapp__media_t_fb3472_idx'), models.Index(fields=['is_published'], name='obeeomaapp__is_publ_34040b_idx')],
            },
        ),
    ]
