# Generated by Django 5.2.8 on 2025-11-28 14:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='token_id',
            field=models.CharField(blank=True, help_text='Flutterwave secure card token for recurring payments.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The associated user/employer account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2035)]),
        ),
    ]
