# Generated by Django 5.2.7 on 2025-11-02 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Stress Management, Anxiety Relief",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji or icon name", max_length=50
                    ),
                ),
                ("color_code", models.CharField(default="#667eea", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resource Category",
                "verbose_name_plural": "Resource Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MentalHealthArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("content", models.TextField()),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, help_text="Short summary", max_length=500
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="articles/"),
                ),
                (
                    "reading_time",
                    models.IntegerField(default=5, help_text="Minutes to read"),
                ),
                ("views", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="obeeomaapp.resourcecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mental Health Article",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="MeditationTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("instructions", models.TextField(help_text="Step-by-step guide")),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("benefits", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="meditation/"),
                ),
                ("times_practiced", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meditations",
                        to="obeeomaapp.resourcecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meditation Technique",
                "ordering": ["difficulty", "title"],
            },
        ),
        migrations.CreateModel(
            name="EducationalVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(help_text="What will users learn?")),
                ("youtube_url", models.URLField(help_text="YouTube video URL")),
                ("thumbnail", models.URLField(blank=True, null=True)),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g., 10:30", max_length=20
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="obeeomaapp.resourcecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Educational Video",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalmingAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(help_text="What does this audio help with?"),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="audios/"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True, help_text="External audio URL", null=True
                    ),
                ),
                ("duration", models.CharField(blank=True, max_length=20)),
                ("plays", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audios",
                        to="obeeomaapp.resourcecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calming Audio",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obeeomaapp.mentalhealtharticle",
                    ),
                ),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obeeomaapp.calmingaudio",
                    ),
                ),
                (
                    "meditation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obeeomaapp.meditationtechnique",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obeeomaapp.educationalvideo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Resource",
                "ordering": ["-saved_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("progress_percentage", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obeeomaapp.mentalhealtharticle",
                    ),
                ),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obeeomaapp.calmingaudio",
                    ),
                ),
                (
                    "meditation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obeeomaapp.meditationtechnique",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obeeomaapp.educationalvideo",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "ordering": ["-accessed_at"],
            },
        ),
    ]
