# Generated by Django 5.2.6 on 2025-10-05 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('GAD-7', 'GAD-7 (Anxiety)'), ('PHQ-9', 'PHQ-9 (Depression)'), ('BOTH', 'Both Assessments')], max_length=10)),
                ('gad7_scores', models.JSONField(blank=True, default=list)),
                ('phq9_scores', models.JSONField(blank=True, default=list)),
                ('gad7_total', models.PositiveIntegerField(default=0)),
                ('phq9_total', models.PositiveIntegerField(default=0)),
                ('gad7_severity', models.CharField(blank=True, max_length=20)),
                ('phq9_severity', models.CharField(blank=True, max_length=20)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mental_health_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
    ]
