# Generated by Django 5.2.6 on 2025-12-07 05:20

from django.db import migrations


def remove_old_fields(apps, schema_editor):
    """
    Manually remove old invitation fields if they exist.
    This handles cases where fields may not exist in all environments.
    """
    db_alias = schema_editor.connection.alias
    
    # Use raw SQL to check and drop columns if they exist
    with schema_editor.connection.cursor() as cursor:
        # Check if columns exist and drop them
        fields_to_remove = ['token', 'expires_at', 'temporary_username', 'temporary_password', 'credentials_used']
        
        for field in fields_to_remove:
            try:
                cursor.execute(f"""
                    ALTER TABLE obeeomaapp_employeeinvitation 
                    DROP COLUMN IF EXISTS {field};
                """)
            except Exception as e:
                # Field doesn't exist or already removed, continue
                print(f"Note: Could not remove {field}: {e}")
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_old_fields, reverse_code=migrations.RunPython.noop),
    ]
