# Generated by Django 5.2.6 on 2025-10-07 07:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0002_mentalhealthassessment'),
    ]

    operations = [
        # First, rename the Organization model to Employer
        migrations.RenameModel(
            old_name='Organization',
            new_name='Employer',
        ),
        # Then rename all the foreign key fields
        migrations.RenameField(
            model_name='aimanagement',
            old_name='organization',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='analyticssnapshot',
            old_name='organization',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='hotlineactivity',
            old_name='organization',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='recentactivity',
            old_name='organization',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='organization',
            new_name='employer',
        ),
        # Update the activity type choices
        migrations.AlterField(
            model_name='recentactivity',
            name='activity_type',
            field=models.CharField(choices=[('New Employer', 'New Employer'), ('AI Management', 'AI Management'), ('Hotline Activity', 'Hotline Activity'), ('Employee Engagement', 'Employee Engagement'), ('Subscription', 'Subscription')], max_length=50),
        ),
        # Remove the unique constraint and organization field from ClientEngagement
        migrations.AlterUniqueTogether(
            name='clientengagement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clientengagement',
            name='organization',
        ),
        # Create the new Employee model (now that Employer exists)
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='obeeomaapp.employer')),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
        # Create the new EmployeeEngagement model
        migrations.CreateModel(
            name='EmployeeEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('month', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='obeeomaapp.employer')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('employer', 'month')},
            },
        ),
        # Finally, delete the old models
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientEngagement',
        ),
    ]
