# Generated by Django 5.2.6 on 2025-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0002_remove_invitation_token_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
