# Generated by Django 5.2.7 on 2025-10-28 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0002_alter_resourcecategory_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
