# Generated by Django 5.2.8 on 2025-11-29 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0002_paymentmethod_token_id_paymentmethod_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSS10Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('responses', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pss10_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
