# Generated by Django 5.2.8 on 2025-12-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0002_remove_invitation_token_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeengagement',
            name='notes',
        ),
    ]
