# Generated by Django 5.2.1 on 2025-09-25 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0002_rename_patientengagement_clientengagement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='revenue',
            new_name='Subscriptions',
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='activity_type',
            field=models.CharField(choices=[('New Organization', 'New Organization'), ('AI Management', 'AI Management'), ('Hotline Activity', 'Hotline Activity'), ('Client Engagement', 'Client Engagement'), ('Subscription', 'Subscription')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=50),
        ),
        migrations.CreateModel(
            name='AIManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('effectiveness', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='obeeomaapp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AIRecommendation',
        ),
    ]
