# Generated by Django 5.2.7 on 2026-02-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0002_chatsession_last_message_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodtracking',
            name='note',
            field=models.TextField(blank=True, help_text='Optional note about the mood entry', null=True),
        ),
    ]
