# Generated by Django 5.2.6 on 2025-09-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0002_rename_patientengagement_clientengagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='activity_type',
            field=models.CharField(choices=[('New Organization', 'New Organization'), ('AI Recommendation', 'AI Recommendation'), ('Hotline Activity', 'Hotline Activity'), ('Client Engagement', 'Client Engagement'), ('Subscription', 'Subscription')], max_length=50),
        ),
    ]
