# Generated by Django 5.2.7 on 2025-10-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0002_classicalarticle_anxietydistressmastery_and_more"),
        ("obeeomaapp", "0002_progress"),
    ]

    operations = []
