# Generated by Django 5.2.6 on 2025-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('starter', 'Starter Plan'), ('enterprise', 'Enterprise Plan')], max_length=50),
        ),
    ]
