# Generated by Django 5.2.1 on 2025-09-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0003_remove_subscription_revenue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Subscriptions',
            new_name='revenue',
        ),
    ]
