# Generated by Django 5.2.8 on 2025-12-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0003_pss10assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodtracking',
            name='note',
        ),
    ]
