# Generated by Django 5.2.7 on 2025-10-28 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0003_merge_20251028_2316"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalmingAudio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Audio track name", max_length=200)),
                ("description", models.TextField(help_text="What this audio helps with")),
                ("audio_file", models.FileField(blank=True, null=True, upload_to="calming_audios/")),
                ("audio_url", models.URLField(blank=True, null=True, help_text="External audio URL (if not uploading file)")),
                ("duration", models.CharField(blank=True, help_text="e.g., 15:00", max_length=20)),
                ("play_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resource_category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calming_audios", to="obeeomaapp.resourcecategory")),
            ],
            options={
                "verbose_name": "Calming Audio",
                "verbose_name_plural": "Calming Audios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuidedMeditation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Meditation technique name", max_length=200)),
                ("description", models.TextField(help_text="What this meditation helps achieve")),
                ("step_by_step_guide", models.TextField(help_text="Detailed instructions for practice")),
                ("duration_minutes", models.IntegerField(help_text="Recommended duration in minutes")),
                ("difficulty_level", models.CharField(choices=[("beginner", "🌱 Beginner - New to meditation"), ("intermediate", "🌿 Intermediate - Some experience"), ("advanced", "🌳 Advanced - Regular practitioner")], default="beginner", max_length=20)),
                ("health_benefits", models.TextField(blank=True, help_text="Mental health benefits of this practice")),
                ("practice_image", models.ImageField(blank=True, null=True, upload_to="meditation_images/")),
                ("times_practiced", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resource_category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guided_meditations", to="obeeomaapp.resourcecategory")),
            ],
            options={
                "verbose_name": "Guided Meditation",
                "verbose_name_plural": "Guided Meditations",
                "ordering": ["difficulty_level", "title"],
            },
        ),
        migrations.CreateModel(
            name="MentalHealthArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Article headline", max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("content", models.TextField(help_text="Full article content")),
                ("excerpt", models.TextField(blank=True, help_text="Short summary for preview", max_length=500)),
                ("featured_image", models.ImageField(blank=True, null=True, upload_to="article_images/")),
                ("estimated_read_time", models.IntegerField(default=5, help_text="Reading time in minutes")),
                ("views_count", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mental_health_articles", to=settings.AUTH_USER_MODEL)),
                ("resource_category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="articles", to="obeeomaapp.resourcecategory")),
            ],
            options={
                "verbose_name": "Mental Health Article",
                "verbose_name_plural": "Mental Health Articles",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="SavedResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("calming_audio", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="obeeomaapp.calmingaudio")),
                ("educational_video", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="obeeomaapp.educationalvideo")),
                ("guided_meditation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="obeeomaapp.guidedmeditation")),
                ("mental_health_article", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="obeeomaapp.mentalhealtharticle")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saved_resources", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Saved Resource",
                "verbose_name_plural": "Saved Resources",
                "ordering": ["-saved_at"],
                "unique_together": {
                    ("user", "calming_audio"),
                    ("user", "educational_video"),
                    ("user", "guided_meditation"),
                    ("user", "mental_health_article"),
                },
            },
        ),
        migrations.CreateModel(
            name="UserLearningProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_completed", models.BooleanField(default=False)),
                ("completion_percentage", models.IntegerField(default=0, help_text="0-100%")),
                ("personal_notes", models.TextField(blank=True, help_text="User's private notes about this resource")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("calming_audio", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="obeeomaapp.calmingaudio")),
                ("educational_video", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="obeeomaapp.educationalvideo")),
                ("guided_meditation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="obeeomaapp.guidedmeditation")),
                ("mental_health_article", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="obeeomaapp.mentalhealtharticle")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="learning_progress", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "User Learning Progress",
                "verbose_name_plural": "User Learning Progress",
                "ordering": ["-last_accessed"],
            },
        ),
    ]
