# Generated by Django 5.2.8 on 2026-02-09 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0003_add_note_to_mood_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymood',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='companymood',
            name='angry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='anxious_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='average_mood_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='calm_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='content_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companymood',
            name='dominant_mood',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='companymood',
            name='ecstatic_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='excited_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='frustrated_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='happy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='negative_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='neutral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='neutral_mood_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_moods', to='obeeomaapp.organization'),
        ),
        migrations.AddField(
            model_name='companymood',
            name='positive_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='sad_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='sentiment_trend',
            field=models.CharField(default='stable', max_length=20),
        ),
        migrations.AddField(
            model_name='companymood',
            name='stressed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='tired_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='total_entries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companymood',
            name='summary_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='companymood',
            unique_together={('organization', 'date')},
        ),
    ]
