# Generated by Django 5.2.7 on 2025-11-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0002_dynamicquestion"),
        ("obeeomaapp", "0003_alter_user_email"),
    ]

    operations = []
