# Generated by Django 5.2.7 on 2025-10-29 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "obeeomaapp",
            "0004_calmingaudio_guidedmeditation_mentalhealtharticle_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uservideointeraction",
            options={"ordering": ["watched_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="uservideointeraction",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="uservideointeraction",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uservideointeraction",
            name="progress",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="uservideointeraction",
            name="mood_after",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uservideointeraction",
            name="mood_before",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("mood_score", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
