# Generated by Django 5.2.7 on 2025-12-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0004_remove_moodtracking_note"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="employeeinvitation",
            name="obeeomaapp__token_873da2_idx",
        ),
        migrations.RenameField(
            model_name="employeeinvitation",
            old_name="expires_at",
            new_name="otp_expires_at",
        ),
        migrations.RemoveField(
            model_name="employeeinvitation",
            name="credentials_used",
        ),
        migrations.RemoveField(
            model_name="employeeinvitation",
            name="temporary_password",
        ),
        migrations.RemoveField(
            model_name="employeeinvitation",
            name="temporary_username",
        ),
        migrations.RemoveField(
            model_name="employeeinvitation",
            name="token",
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_first_time",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="employeeinvitation",
            index=models.Index(fields=["email"], name="obeeomaapp__email_d19f8c_idx"),
        ),
    ]
