# Generated by Django 5.2.7 on 2025-10-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0004_employee_first_name_employee_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservideointeraction",
            name="mood_after",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uservideointeraction",
            name="mood_before",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
