# Generated by Django 5.2.7 on 2026-02-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "obeeomaapp",
            "0004_alter_companymood_options_companymood_angry_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contentmedia",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meditation", "Meditation"),
                    ("sleep", "Sleep"),
                    ("anxiety", "Anxiety Relief"),
                    ("stress", "Stress Management"),
                    ("mindfulness", "Mindfulness"),
                    ("general", "General Wellness"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contentmedia",
            name="duration",
            field=models.CharField(blank=True, help_text="e.g., 3:00", max_length=20),
        ),
        migrations.AddField(
            model_name="contentmedia",
            name="file_size",
            field=models.CharField(
                blank=True, help_text="e.g., 15.2 MB", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="contentmedia",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("processing", "Processing"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contentmedia",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="contentmedia",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
