# Generated by Django 5.2.6 on 2025-11-11 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0004_alter_employeeinvitation_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sleep', 'Sleep'), ('gratitude', 'Gratitude'), ('happiness', 'Happiness'), ('meditation', 'Meditation'), ('mindfulness', 'Mindfulness'), ('breathing', 'Breathing')], max_length=50, unique=True)),
                ('icon', models.CharField(help_text='Icon name or emoji', max_length=100)),
                ('color', models.CharField(default='#4CAF50', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Meditation Category',
                'verbose_name_plural': 'Meditation Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('systemadmin', 'Systemadmin'), ('organisation', 'Organisation'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(auto_now=True)),
                ('total_days_active', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Streak',
                'verbose_name_plural': 'Daily Streaks',
            },
        ),
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(help_text='Thumbnail image', upload_to='featured_content/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='meditation_audio/')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_content', to='obeeomaapp.meditationcategory')),
            ],
            options={
                'verbose_name': 'Featured Content',
                'verbose_name_plural': 'Featured Content',
                'ordering': ['-is_featured', '-play_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('featured_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obeeomaapp.featuredcontent')),
                ('meditation_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obeeomaapp.meditationtechnique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meditation Session',
                'verbose_name_plural': 'Meditation Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('pattern', 'Pattern Recognition'), ('trigger', 'Trigger Identification'), ('recommendation', 'Recommendation'), ('achievement', 'Achievement'), ('warning', 'Warning')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Insight',
                'verbose_name_plural': 'Mood Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('positive_mood_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('most_common_mood', models.CharField(blank=True, max_length=20)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Days with consecutive entries')),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_entry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mood_pattern', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Pattern',
                'verbose_name_plural': 'Mood Patterns',
            },
        ),
        migrations.CreateModel(
            name='DailyMoodCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('bad', 'Bad')], max_length=10)),
                ('note', models.TextField(blank=True, help_text='Optional note about the mood')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_moods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Mood Check-in',
                'verbose_name_plural': 'Daily Mood Check-ins',
                'ordering': ['-checked_in_at'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('sad', 'Sad'), ('neutral', 'Neutral'), ('happy', 'Happy'), ('calm', 'Calm'), ('excited', 'Excited'), ('anxious', 'Anxious'), ('stressed', 'Stressed'), ('angry', 'Angry'), ('grateful', 'Grateful'), ('tired', 'Tired'), ('energetic', 'Energetic'), ('lonely', 'Lonely'), ('loved', 'Loved'), ('hopeful', 'Hopeful'), ('overwhelmed', 'Overwhelmed')], max_length=20)),
                ('note', models.TextField(blank=True, help_text="What's on your mind?")),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activities', models.JSONField(blank=True, default=list, help_text='Activities done today')),
                ('energy_level', models.IntegerField(default=5, help_text='Energy level 1-10')),
                ('sleep_quality', models.IntegerField(blank=True, help_text='Sleep quality 1-10', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Entry',
                'verbose_name_plural': 'Mood Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='obeeomaapp__user_id_9840c5_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('featured_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obeeomaapp.featuredcontent')),
                ('meditation_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obeeomaapp.meditationtechnique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Favorite',
                'verbose_name_plural': 'User Favorites',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'featured_content'), ('user', 'meditation_technique')},
            },
        ),
    ]
