# Generated by Django 5.2.8 on 2025-12-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0004_remove_moodtracking_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeengagement',
            old_name='notes',
            new_name='name',
        ),
        migrations.AddField(
            model_name='employeeengagement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeeengagement',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeengagement',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeengagement',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
