# Generated by Django 5.2.1 on 2025-10-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0005_passwordresettoken"),
        ("obeeomaapp", "0005_resourcecategory"),
    ]

    operations = []
