# Generated by Django 5.2.6 on 2025-12-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0005_companymood_engagementlevel_employee_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinvitation',
            name='employeedepartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeinvitation',
            name='employeename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeinvitation',
            name='employeephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
