# Generated by Django 5.2.6 on 2025-11-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0002_remove_wellnesstest_department_and_more'),
        ('obeeomaapp', '0005_meditationcategory_alter_user_role_dailystreak_and_more'),
    ]

    operations = [
    ]
