# Generated by Django 5.2.7 on 2026-02-19 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0005_contentmedia_category_contentmedia_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("admin", "Admin"), ("ai", "AI Assistant")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        limit_choices_to={"role": "system_admin"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["admin", "timestamp"],
                        name="obeeomaapp__admin_i_e83cd6_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="obeeomaapp__timesta_0acf8c_idx"
                    ),
                ],
            },
        ),
    ]
