# Generated by Django 5.2.7 on 2026-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0006_admin_chat_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymood",
            name="ecstatic_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="ReceptionistChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(default="default", max_length=255)),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "User"), ("ai", "AI Receptionist")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "timestamp"],
                        name="obeeomaapp__session_438d45_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="obeeomaapp__timesta_3fd011_idx"
                    ),
                ],
            },
        ),
    ]
