# Generated by Django 5.2.6 on 2025-11-12 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0006_merge_20251112_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystreak',
            name='user',
        ),
        migrations.RemoveField(
            model_name='featuredcontent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='featured_content',
        ),
        migrations.RemoveField(
            model_name='meditationsession',
            name='featured_content',
        ),
        migrations.RemoveField(
            model_name='meditationsession',
            name='meditation_technique',
        ),
        migrations.RemoveField(
            model_name='meditationsession',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='moodinsight',
            name='user',
        ),
        migrations.RemoveField(
            model_name='moodpattern',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='meditation_technique',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='user',
        ),
        migrations.AlterField(
            model_name='moodtracking',
            name='mood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('PHQ-9', 'Patient Health Questionnaire (PHQ-9)'), ('GAD-7', 'Generalized Anxiety Disorder (GAD-7)')], max_length=10)),
                ('question_number', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assessment Question',
                'verbose_name_plural': 'Assessment Questions',
                'ordering': ['assessment_type', 'question_number'],
                'unique_together': {('assessment_type', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('PHQ-9', 'PHQ-9'), ('GAD-7', 'GAD-7')], max_length=10)),
                ('responses', models.JSONField(help_text='Array of scores for each question')),
                ('total_score', models.PositiveIntegerField()),
                ('severity_level', models.CharField(max_length=50)),
                ('difficulty_level', models.CharField(blank=True, choices=[('not_difficult', 'Not difficult at all'), ('somewhat_difficult', 'Somewhat difficult'), ('very_difficult', 'Very Difficult'), ('extremely_difficult', 'Extremely Difficult')], max_length=30, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Response',
                'verbose_name_plural': 'Assessment Responses',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='WellnessHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checkin_date', models.DateField(blank=True, null=True)),
                ('last_checkin_mood', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('stressed', 'Stressed'), ('anxious', 'Anxious'), ('neutral', 'Neutral')], max_length=20, null=True)),
                ('mood_logs', models.JSONField(blank=True, default=list)),
                ('mood_insights', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_hub', to='obeeomaapp.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WellnessTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('wellbeing_check', 'Well-being Check'), ('burnout_risk', 'Burnout Risk'), ('stress_assessment', 'Stress Assessment')], max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obeeomaapp.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_tests', to='obeeomaapp.employee')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.DeleteModel(
            name='DailyMoodCheckin',
        ),
        migrations.DeleteModel(
            name='DailyStreak',
        ),
        migrations.DeleteModel(
            name='MeditationCategory',
        ),
        migrations.DeleteModel(
            name='FeaturedContent',
        ),
        migrations.DeleteModel(
            name='MeditationSession',
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
        migrations.DeleteModel(
            name='MoodInsight',
        ),
        migrations.DeleteModel(
            name='MoodPattern',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
