# Generated by Django 5.2.1 on 2025-10-20 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0006_merge_0005_passwordresettoken_0005_resourcecategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Video title", max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="What viewers will learn from this video"
                    ),
                ),
                ("youtube_url", models.URLField(help_text="YouTube video URL")),
                ("thumbnail", models.URLField(blank=True, null=True)),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g., 10:30", max_length=20
                    ),
                ),
                (
                    "target_mood",
                    models.CharField(
                        choices=[
                            ("anxiety", "Anxiety Relief"),
                            ("depression", "Depression Support"),
                            ("stress", "Stress Management"),
                            ("mindfulness", "Mindfulness & Meditation"),
                            ("self_esteem", "Self-Esteem Building"),
                            ("coping", "Coping Skills"),
                            ("sleep", "Sleep Improvement"),
                            ("anger", "Anger Management"),
                            ("grief", "Grief & Loss"),
                            ("general", "General Wellness"),
                        ],
                        help_text="What mental health challenge does this video address?",
                        max_length=50,
                    ),
                ),
                (
                    "intensity_level",
                    models.IntegerField(
                        choices=[
                            (1, "Gentle - For difficult moments"),
                            (2, "Moderate - Daily practice"),
                            (3, "Deep - Intensive work"),
                        ],
                        default=1,
                        help_text="How intense is this content?",
                    ),
                ),
                (
                    "crisis_support_text",
                    models.TextField(
                        blank=True,
                        help_text="Crisis resources to show after video (hotlines, emergency contacts)",
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                (
                    "helpful_count",
                    models.IntegerField(
                        default=0, help_text="Number of users who found this helpful"
                    ),
                ),
                (
                    "saved_count",
                    models.IntegerField(
                        default=0, help_text="Number of users who saved this video"
                    ),
                ),
                ("is_professionally_reviewed", models.BooleanField(default=False)),
                (
                    "reviewed_by",
                    models.CharField(
                        blank=True,
                        help_text="Professional who reviewed this",
                        max_length=100,
                    ),
                ),
                ("review_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educational_videos",
                        to="obeeomaapp.resourcecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Educational Video",
                "verbose_name_plural": "Educational Videos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserVideoInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood_before",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Very distressed"),
                            (2, "Somewhat distressed"),
                            (3, "Neutral"),
                            (4, "Somewhat calm"),
                            (5, "Very calm"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "mood_after",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Much worse"),
                            (2, "Slightly worse"),
                            (3, "No change"),
                            (4, "Slightly better"),
                            (5, "Much better"),
                        ],
                        null=True,
                    ),
                ),
                ("watched_full_video", models.BooleanField(default=False)),
                ("marked_helpful", models.BooleanField(default=False)),
                ("saved_for_later", models.BooleanField(default=False)),
                ("watched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obeeomaapp.educationalvideo",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="educationalvideo",
            index=models.Index(
                fields=["target_mood", "intensity_level"],
                name="obeeomaapp__target__1f91ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="educationalvideo",
            index=models.Index(
                fields=["is_active", "is_professionally_reviewed"],
                name="obeeomaapp__is_acti_4991bd_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="uservideointeraction",
            unique_together={("user", "video")},
        ),
    ]
