# Generated by Django 5.2.6 on 2025-12-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0006_employeeinvitation_employeedepartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinvitation',
            name='employeename',
        ),
    ]
