# Generated by Django 5.2.7 on 2026-03-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0006_admin_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymood',
            name='ecstatic_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
