# Generated by Django 5.2.7 on 2025-12-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0007_remove_employeeinvitation_employeename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeinvitation",
            name="accepted",
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
