# Generated by Django 5.2.7 on 2026-03-04 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0007_alter_companymood_ecstatic_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(
                        choices=[
                            ("landing_ai", "Landing Page AI"),
                            ("admin_ai", "Admin Dashboard AI"),
                            ("mobile_ai", "Mobile App AI"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_status_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["feature_name"],
                "indexes": [
                    models.Index(
                        fields=["feature_name"], name="obeeomaapp__feature_7a4d33_idx"
                    ),
                    models.Index(
                        fields=["is_enabled"], name="obeeomaapp__is_enab_162826_idx"
                    ),
                ],
            },
        ),
    ]
