# Generated by Django 5.2.6 on 2025-10-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0005_passwordresettoken'),
        ('obeeomaapp', '0007_subscriptionplan_alter_subscription_options_and_more'),
    ]

    operations = [
    ]
