# Generated by Django 5.2.7 on 2025-11-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0007_remove_dailystreak_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="obeeomaapp.educationalresource",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="target_mood",
            field=models.CharField(
                choices=[
                    ("anxiety", "Anxiety Relief"),
                    ("depression", "Depression Support"),
                    ("stress", "Stress Management"),
                    ("mindfulness", "Mindfulness & Meditation"),
                    ("self_esteem", "Self-Esteem Building"),
                    ("coping", "Coping Skills"),
                    ("sleep", "Sleep Improvement"),
                    ("anger", "Anger Management"),
                    ("grief", "Grief & Loss"),
                    ("general", "General Wellness"),
                    ("sad", "Sadness Support"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
