# Generated by Django 5.2.7 on 2025-12-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0008_remove_employeeinvitation_accepted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodtracking",
            name="mood",
            field=models.CharField(
                choices=[
                    ("Ecstatic", "Ecstatic"),
                    ("Happy", "Happy"),
                    ("Excited", "Excited"),
                    ("Content", "Content"),
                    ("Calm", "Calm"),
                    ("Neutral", "Neutral"),
                    ("Tired", "Tired"),
                    ("Anxious", "Anxious"),
                    ("Stressed", "Stressed"),
                    ("Sad", "Sad"),
                    ("Frustrated", "Frustrated"),
                    ("Angry", "Angry"),
                ],
                default="Neutral",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
