# Generated by Django 5.2.7 on 2026-03-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0007_alter_companymood_ecstatic_count"),
        ("obeeomaapp", "0008_aistatus"),
    ]

    operations = []
