# Generated by Django 5.2.8 on 2025-12-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0003_remove_employeeengagement_notes'),
        ('obeeomaapp', '0008_remove_employeeinvitation_accepted_and_more'),
    ]

    operations = [
    ]
