# Generated by Django 5.2.7 on 2025-11-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0008_alter_video_category_alter_video_target_mood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audios",
                to="obeeomaapp.educationalresource",
            ),
        ),
    ]
