# Generated by Django 5.2.6 on 2025-11-15 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0009_alter_audio_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('PHQ-9', 'PHQ-9 (Depression)'), ('GAD-7', 'GAD-7 (Anxiety)')], max_length=10)),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['assessment_type', 'question_number'],
                'unique_together': {('assessment_type', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('PHQ-9', 'PHQ-9'), ('GAD-7', 'GAD-7')], max_length=10)),
                ('total_score', models.IntegerField()),
                ('severity_level', models.CharField(max_length=50)),
                ('responses', models.JSONField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
