# Generated by Django 5.2.7 on 2025-11-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0010_add_assessment_question_response"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessmentquestion",
            options={
                "ordering": ["assessment_type", "question_number"],
                "verbose_name": "Assessment Question",
                "verbose_name_plural": "Assessment Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="assessmentresponse",
            options={
                "ordering": ["-completed_at"],
                "verbose_name": "Assessment Response",
                "verbose_name_plural": "Assessment Responses",
            },
        ),
        migrations.RemoveField(
            model_name="contactperson",
            name="fullname",
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_difficult", "Not difficult at all"),
                    ("somewhat_difficult", "Somewhat difficult"),
                    ("very_difficult", "Very Difficult"),
                    ("extremely_difficult", "Extremely Difficult"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contactperson",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contactperson",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="assessmentquestion",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("PHQ-9", "Patient Health Questionnaire (PHQ-9)"),
                    ("GAD-7", "Generalized Anxiety Disorder (GAD-7)"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="assessmentquestion",
            name="question_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="assessmentresponse",
            name="responses",
            field=models.JSONField(help_text="Array of scores for each question"),
        ),
        migrations.AlterField(
            model_name="assessmentresponse",
            name="total_score",
            field=models.PositiveIntegerField(),
        ),
    ]
