# Generated by Django 5.2.8 on 2025-12-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0009_alter_moodtracking_mood'),
        ('obeeomaapp', '0010_alter_chatmessage_options'),
    ]

    operations = [
    ]
