# Generated by Django 5.2.8 on 2025-12-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0011_merge_20251222_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodtracking',
            name='mood',
            field=models.CharField(choices=[('Ecstatic', 'Ecstatic'), ('Happy', 'Happy'), ('Excited', 'Excited'), ('Content', 'Content'), ('Calm', 'Calm'), ('Neutral', 'Neutral'), ('Tired', 'Tired'), ('Anxious', 'Anxious'), ('Stressed', 'Stressed'), ('Sad', 'Sad'), ('Frustrated', 'Frustrated'), ('Angry', 'Angry')], default='Neutral', max_length=50),
        ),
    ]
