# Generated by Django 5.2.7 on 2025-11-18 05:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0011_alter_assessmentquestion_options_and_more"),
    ]

    operations = [
        # Ensure these fields exist
        migrations.AlterField(
            model_name='contactperson',
            name='first_name',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='last_name',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(),
        ),
    ]
