# Generated by Django 5.2.7 on 2025-12-29 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0012_alter_moodtracking_mood"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="contactPerson",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="password",
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_person",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "employer"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_organization",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name="ContactPerson",
        ),
    ]
