# Generated by Django 5.2.7 on 2025-12-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "obeeomaapp",
            "0013_alter_article_options_article_author_article_excerpt_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
