# Generated by Django 5.2.7 on 2025-12-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0014_alter_organization_contact_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="organizationName",
            field=models.CharField(max_length=255),
        ),
    ]
