# Generated by Django 5.2.7 on 2025-11-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0014_contactperson_add_name_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="notification",
            name="content_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="obeeomaapp.organization",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
