# Generated by Django 5.2.6 on 2025-11-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0015_achievement_remove_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinvitation',
            name='credentials_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeinvitation',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employeeinvitation',
            name='temporary_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'Systems Admin'), ('employer', 'Employer'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
