# Generated by Django 5.2.7 on 2025-11-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0015_achievement_remove_video_thumbnail_and_more"),
        (
            "obeeomaapp",
            "0015_remove_video_thumbnail_notification_content_type_and_more",
        ),
    ]

    operations = []
