# Generated by Django 5.2.7 on 2025-12-30 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0015_alter_organization_organizationname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "employer"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
