# Generated by Django 5.2.7 on 2025-11-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0017_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organizationName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
