# Generated by Django 5.2.8 on 2026-01-07 08:58

import django.core.validators
import obeeomaapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0017_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', obeeomaapp.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2036)]),
        ),
    ]
