# Generated by Django 5.2.7 on 2025-11-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0016_add_temporary_credentials_to_invitation"),
        ("obeeomaapp", "0018_alter_organization_organizationname"),
    ]

    operations = []
