# Generated by Django 5.2.7 on 2026-01-07 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0018_alter_user_managers_alter_paymentmethod_expiry_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("sana_ai", "Sana AI"),
                            ("journaling", "Journaling"),
                            ("education", "Educational Resources"),
                            ("assessment", "Self Assessment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("first_used_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Usage",
                "verbose_name_plural": "Feature Usages",
                "unique_together": {("user", "feature")},
            },
        ),
    ]
