# Generated by Django 5.2.7 on 2025-11-22 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0019_merge_20251122_1312"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivity",
            name="audio",
        ),
        migrations.RemoveField(
            model_name="userlearningprogress",
            name="audio",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="is_published",
            new_name="is_public",
        ),
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.RemoveField(
            model_name="article",
            name="excerpt",
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="educationalresource",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="progress",
            name="date",
        ),
        migrations.RemoveField(
            model_name="progress",
            name="mood_score",
        ),
        migrations.RemoveField(
            model_name="progress",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="video",
            name="crisis_support_text",
        ),
        migrations.RemoveField(
            model_name="video",
            name="description",
        ),
        migrations.RemoveField(
            model_name="video",
            name="is_professionally_reviewed",
        ),
        migrations.RemoveField(
            model_name="video",
            name="youtube_url",
        ),
        migrations.AddField(
            model_name="progress",
            name="articles_read",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="progress",
            name="assessments_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="progress",
            name="chats_with_sana",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="progress",
            name="journals_written",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="progress",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="progress",
            name="mood",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="progress",
            name="videos_watched",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="educationalresource",
            name="resource_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pdf", "PDF"),
                    ("CBTExercise", "CBT Exercise"),
                    ("video", "Video"),
                    ("article", "Article"),
                    ("meditation technique", "Meditation Technique"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CBTExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("thought_record", "Thought Record"),
                            ("behavioral_activation", "Behavioral Activation"),
                            ("cognitive_restructuring", "Cognitive Restructuring"),
                            ("exposure", "Exposure"),
                            ("gratitude", "Gratitude"),
                            ("mindfulness", "Mindfulness"),
                        ],
                        max_length=40,
                    ),
                ),
                ("estimated_minutes", models.PositiveIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("is_professionally_reviewed", models.BooleanField(default=False)),
                ("reviewed_by", models.CharField(blank=True, max_length=100)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("views_count", models.IntegerField(default=0)),
                ("helpful_count", models.IntegerField(default=0)),
                ("saved_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbt_exercises",
                        to="obeeomaapp.educationalresource",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="savedresource",
            unique_together={
                ("user", "article"),
                ("user", "meditation"),
                ("user", "video"),
            },
        ),
        migrations.AddField(
            model_name="savedresource",
            name="cbt_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="obeeomaapp.cbtexercise",
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="cbt_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="obeeomaapp.cbtexercise",
            ),
        ),
        migrations.AddField(
            model_name="userlearningprogress",
            name="cbt_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="obeeomaapp.cbtexercise",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedresource",
            unique_together={
                ("user", "article"),
                ("user", "cbt_exercise"),
                ("user", "meditation"),
                ("user", "video"),
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("note", "Note"), ("audio", "Audio")],
                        default="note",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="journal_audio/"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="savedresource",
            name="audio",
        ),
        migrations.DeleteModel(
            name="Audio",
        ),
    ]
