# Generated by Django 5.2.7 on 2025-11-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0020_remove_useractivity_audio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_date"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
