# Generated by Django 5.2.8 on 2026-01-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0020_remove_notification_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
    ]
