# Generated by Django 5.2.7 on 2025-11-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0019_merge_20251121_0923"),
        ("obeeomaapp", "0021_alter_article_options"),
    ]

    operations = []
