# Generated by Django 5.2.8 on 2026-01-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0021_remove_notification_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('assessment', 'Assessment'), ('moodtracking', 'Mood Tracking'), ('yourprogress', 'Your Progress'), ('educationalresource', 'Educational Resource')], max_length=30),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='target_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of actions required to unlock this achievement. Leave blank for one-time achievements.', null=True),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='obeeomaapp.achievement'),
        ),
    ]
