# Generated by Django 5.2.8 on 2026-01-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0019_featureusage'),
        ('obeeomaapp', '0022_alter_achievement_category_and_more'),
    ]

    operations = [
    ]
