# Generated by Django 5.2.6 on 2026-01-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0023_merge_20260108_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public display name for privacy', max_length=100, null=True),
        ),
    ]
