# Generated by Django 5.2.7 on 2026-01-09 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0023_merge_20260108_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Public name shown in the app",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="subscription_tier",
            field=models.CharField(
                choices=[("freemium", "Freemium"), ("premium", "Premium")],
                default="freemium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_public_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
