# Generated by Django 5.2.7 on 2026-01-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obeeomaapp", "0025_article_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
