# Generated by Django 5.2.7 on 2026-01-13 07:45

from django.db import migrations, models


def safe_article_migration(apps, schema_editor):
    """
    Safely migrate Article model to new structure
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check what columns exist
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'obeeomaapp_article'
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        # Add missing columns only if they don't exist
        if 'excerpt' not in existing_columns:
            cursor.execute("""
                ALTER TABLE obeeomaapp_article 
                ADD COLUMN excerpt TEXT;
            """)
        
        if 'status' not in existing_columns:
            cursor.execute("""
                ALTER TABLE obeeomaapp_article 
                ADD COLUMN status VARCHAR(10) DEFAULT 'draft';
            """)
        
        if 'featured' not in existing_columns:
            cursor.execute("""
                ALTER TABLE obeeomaapp_article 
                ADD COLUMN featured BOOLEAN DEFAULT FALSE;
            """)
        
        # Handle category field conversion from ForeignKey to CharField
        if 'category_id' in existing_columns and 'category' not in existing_columns:
            # Add new category column
            cursor.execute("""
                ALTER TABLE obeeomaapp_article 
                ADD COLUMN category VARCHAR(100);
            """)
            
            # Set default values for existing records
            cursor.execute("""
                UPDATE obeeomaapp_article 
                SET category = 'General' 
                WHERE category_id IS NOT NULL;
            """)
            
            # Drop the foreign key column
            cursor.execute("""
                ALTER TABLE obeeomaapp_article 
                DROP COLUMN category_id CASCADE;
            """)
        
        # Update author field length if needed
        try:
            cursor.execute("""
                ALTER TABLE obeeomaapp_article 
                ALTER COLUMN author TYPE VARCHAR(100);
            """)
        except:
            pass  # Column might already be correct type


def reverse_safe_article_migration(apps, schema_editor):
    """
    Reverse migration - not implemented as it's complex
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0026_alter_article_author'),
    ]

    operations = [
        migrations.RunPython(safe_article_migration, reverse_safe_article_migration),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date']},
        ),
    ]
