# Generated by Django 5.2.7 on 2026-01-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeeomaapp', '0027_auto_20260113_1045'),
    ]

    operations = [
        # This migration represents the current state of the Article model
        # The actual database changes were already applied in migration 0027
        # This is just to sync Django's migration state with the actual model
    ]
