# sana_ai/services/openai_chat.py

import os
from dotenv import load_dotenv
import openai

# Load environment variables from .env file
load_dotenv()

# Initialize OpenAI client using the API key from environment
openai_client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def get_chat_response(prompt: str) -> str:
    """
    Sends a prompt to OpenAI GPT-3.5 and returns the chatbot's response.

    Args:
        prompt (str): The user's input message.

    Returns:
        str: The chatbot's reply generated by the model.
    """
    # Create a chat completion using the new client-based API
    response = openai_client.chat.completions.create(
        model="gpt-3.5-turbo",  # Specify the model to use
        messages=[
            {"role": "user", "content": prompt}  # Format required by chat models
        ],
        temperature=0.8,  # Controls creativity (0 = deterministic, 1 = creative)
    )

    # Extract and return the generated message content
    return response.choices[0].message.content
